[package]
name = "transaction_signing"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.5"
sp-core = "4.0.0-dev"
hex = "0.4.3"
lazy_static = "1.4.0"
constants = {path = "../constants"}
definitions = {path = "../definitions"}
db_handling = {path = "../db_handling"}
qrcode_static = {path = "../qrcode_static"}
transaction_parsing = {path = "../transaction_parsing"}
sled = "0.34.6"
parity-scale-codec = "2.2.0"
anyhow = "1.0.42"
blake2-rfc = "0.2.18"

[patch.crates-io]
sp-arithmetic = { git = 'https://github.com/paritytech/substrate/' }
sp-runtime = { git = 'https://github.com/paritytech/substrate/' }
sp-core = { git = 'https://github.com/paritytech/substrate/' }
