[package]
name = "qr_reader_phone"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
anyhow = "1.0.42"
raptorq = "1.6.4"
serde_json = "1.0.64"
qrcode_rtx = {path = "../qrcode_rtx"}

[lib]
name = "qr_reader_phone"
crate-type = ["lib"]
