name:                   Rust backend test for android

on:
  pull_request:
  push:
    branches:
      - master
      - stable
jobs:
  check:
    name:               Check
    runs-on:            ubuntu-latest
    steps:
      - name:           Checkout sources
        uses:           actions/checkout@v2
        with:
          fetch-depth:  50

      - name:           Install system dependancies
        run:            |
          sudo apt update
          sudo apt install -y clang libclang-dev libopencv-dev
        shell:          bash

      - name:           Checkout submodules
        shell:          bash
        run:            git submodule update --init --recursive
      - name:           cargo test
        shell:          bash
        run:            |
                        cd rust 
                        cp os-specific-lock/android/Cargo.lock . 
                        cargo test 
                        cd ..
